# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2020-08-11 01:10
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='Tytuł')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start')),
                ('end_date', models.DateTimeField(db_index=True, verbose_name='Zakończenie')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Dane')),
                ('images_count', models.IntegerField(default=-1, verbose_name='Liczba zdjęć (nieważne tutaj)')),
                ('added_time', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
                ('ref_id', models.CharField(blank=True, max_length=15, null=True, verbose_name='Nr ref.')),
                ('min_image', models.FileField(blank=True, upload_to='auction_photos', verbose_name='Male zdjecie')),
                ('highlighted', models.BooleanField(default=False, verbose_name='Wyróżnienie')),
                ('provider_name', models.CharField(max_length=31, verbose_name='Ubezp.')),
                ('provider_id', models.CharField(max_length=127, verbose_name='ID ubezp.')),
                ('published', models.BooleanField(db_index=True, default=True, verbose_name='Opublikowany')),
                ('production_date', models.DateField(verbose_name='Data prod.')),
                ('run', models.IntegerField(verbose_name='Przebieg')),
            ],
            options={
                'verbose_name': 'Aukcja',
                'verbose_name_plural': 'Aukcje',
            },
        ),
        migrations.CreateModel(
            name='AuctionPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='auction_photos')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='rest_api.Auction')),
            ],
            options={
                'verbose_name': 'Zdjecie aukcji',
                'verbose_name_plural': 'Zdjecia aukcji',
            },
        ),
        migrations.CreateModel(
            name='AuctionUserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, help_text='Imie', max_length=127, null=True, verbose_name='Imie')),
                ('last_name', models.CharField(blank=True, help_text='Nazwisko', max_length=127, null=True, verbose_name='Nazwisko')),
                ('address', models.CharField(blank=True, help_text='Adres', max_length=127, null=True, verbose_name='Adres')),
                ('city', models.CharField(blank=True, help_text='Miasto', max_length=127, null=True, verbose_name='Miasto')),
                ('country', models.CharField(blank=True, help_text='Kraj', max_length=127, null=True, verbose_name='Kraj')),
                ('postcode', models.CharField(blank=True, help_text='Kod pocztowy', max_length=127, null=True, verbose_name='Kod pocztowy')),
                ('nip', models.CharField(blank=True, help_text='NIP', max_length=127, null=True, verbose_name='NIP')),
                ('accepted', models.BooleanField(default=False)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Auction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuctionUserFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded', models.FileField(upload_to='user_files')),
                ('comment', models.CharField(blank=True, help_text='Komentarz do pliku', max_length=255, null=True, verbose_name='Komentarz')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Auction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plik dokumentu użytkownika',
                'verbose_name_plural': 'Pliki dokumentów użytkowników',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='Nazwa')),
                ('min_image', models.FileField(blank=True, upload_to='static/website', verbose_name='Baner')),
                ('published', models.BooleanField(db_index=True, default=True, verbose_name='Opublikowany')),
            ],
            options={
                'verbose_name': 'Baner',
                'verbose_name_plural': 'Banery',
            },
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=True, verbose_name='Zaakceptowano')),
                ('price', models.IntegerField(verbose_name='Cena [CHF]')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data wbicia')),
                ('sms_sent', models.BooleanField(default=False, verbose_name='Wyslano SMS')),
                ('betted', models.BooleanField(default=False, verbose_name='Wbita')),
                ('note', models.TextField(blank=True, default='', null=True, verbose_name='Notka')),
                ('color', models.IntegerField(choices=[(0, 'Biały'), (1, 'Zielony'), (2, 'Niebieski'), (3, 'Pomarańczowy'), (4, 'Czerwony'), (5, 'Złoty')], default=0, verbose_name='Kolor')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Auction', verbose_name='Aukcja')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Licytacja',
                'verbose_name_plural': 'Licytacje',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Języki',
                'verbose_name_plural': 'Języki',
            },
        ),
        migrations.CreateModel(
            name='ScheduledBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Cena sugerowana [CHF]')),
                ('price_max', models.IntegerField(verbose_name='Cena maksymalna [CHF]')),
                ('betted', models.BooleanField(default=False, editable=False, verbose_name='Wbita')),
                ('scheduled', models.BooleanField(default=False, editable=False, verbose_name='Rozpoczęto')),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Bet', verbose_name='Licytacja')),
            ],
            options={
                'verbose_name': 'Zaplanowana licytacja',
                'verbose_name_plural': 'Zaplanowane licytacje',
            },
        ),
        migrations.CreateModel(
            name='ShortUrlModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Tytuł')),
                ('url', models.CharField(max_length=2000, verbose_name='URL')),
                ('short_url', models.CharField(max_length=40, verbose_name='Krótki URL')),
            ],
            options={
                'verbose_name': 'Krótkie linki',
                'verbose_name_plural': 'Krótkie linki',
            },
        ),
        migrations.CreateModel(
            name='TopAuction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, help_text='Nie ustawiać, gdy wyżej wybrano aukcje', null=True, upload_to='auction_photos', verbose_name='Zdjęcie')),
                ('title', models.CharField(blank=True, help_text='Można ustawić tytuł, nawet gdy wybrano aukcje', max_length=127, null=True, verbose_name='Tytuł')),
                ('link', models.CharField(blank=True, help_text='Link po kliknięciu w zdjęcie, nie ustawiać gdy wybrano aukcje', max_length=127, null=True, verbose_name='Link')),
                ('auction', models.ForeignKey(blank=True, help_text='Można wybrać aukcję lub ustawić własne zdjęcie z własnym tytułem', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='rest_api.Auction', verbose_name='Aukcja')),
            ],
            options={
                'verbose_name': 'Aukcja dnia',
                'verbose_name_plural': 'Aukcje dnia',
            },
        ),
        migrations.CreateModel(
            name='UserBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False, verbose_name='Zaakceptowano')),
                ('first_name', models.CharField(blank=True, max_length=31, null=True, verbose_name='Imię')),
                ('second_name', models.CharField(blank=True, max_length=31, null=True, verbose_name='Drugie imię')),
                ('last_name', models.CharField(blank=True, max_length=31, null=True, verbose_name='Nazwisko')),
                ('phone_number', models.CharField(blank=True, max_length=31, null=True, verbose_name='Telefon')),
                ('slug', models.CharField(blank=True, max_length=31, null=True, verbose_name='slug')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Notka')),
                ('lang', models.CharField(choices=[('pl', 'Polski'), ('en', 'Angielski'), ('ru', 'Rosyjski'), ('de', 'Niemiecki')], default='pl', max_length=3, verbose_name='Język')),
                ('business_name', models.CharField(blank=True, max_length=63, null=True, verbose_name='Nazwa firmy')),
                ('nip_code', models.CharField(blank=True, max_length=63, null=True, verbose_name='NIP')),
                ('country', models.CharField(blank=True, max_length=63, null=True, verbose_name='Kraj')),
                ('postal_code', models.CharField(blank=True, max_length=31, null=True, verbose_name='Kod poczt.')),
                ('city_name', models.CharField(blank=True, max_length=31, null=True, verbose_name='Miasto')),
                ('street_name', models.CharField(blank=True, max_length=127, null=True, verbose_name='Ulica')),
                ('home_number', models.CharField(blank=True, max_length=63, null=True, verbose_name='Dom/Mieszkanie')),
                ('promocode', models.CharField(blank=True, max_length=63, null=True, verbose_name='Kod promo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uzytkownik biznesowy - firma',
                'verbose_name_plural': 'Uzytkownicy biznesowi - firmy',
            },
        ),
        migrations.CreateModel(
            name='UserPrivate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False, verbose_name='Zaakceptowano')),
                ('first_name', models.CharField(blank=True, max_length=31, null=True, verbose_name='Imię')),
                ('second_name', models.CharField(blank=True, max_length=31, null=True, verbose_name='Drugie imię')),
                ('last_name', models.CharField(blank=True, max_length=63, null=True, verbose_name='Nazwisko')),
                ('phone_number', models.CharField(blank=True, max_length=31, null=True, verbose_name='Telefon')),
                ('slug', models.CharField(blank=True, max_length=31, null=True, verbose_name='slug')),
                ('note', models.TextField(blank=True, max_length=255, null=True, verbose_name='Notka')),
                ('lang', models.CharField(choices=[('pl', 'Polski'), ('en', 'Angielski'), ('ru', 'Rosyjski'), ('de', 'Niemiecki')], default='pl', max_length=3, verbose_name='Język')),
                ('token', models.CharField(blank=True, max_length=127, null=True, verbose_name='Reset token')),
                ('token_end_of_validity', models.DateTimeField(blank=True, null=True, verbose_name='Ważność tokena')),
                ('country', models.CharField(blank=True, max_length=63, null=True, verbose_name='Kraj')),
                ('postal_code', models.CharField(blank=True, max_length=31, null=True, verbose_name='Kod poczt.')),
                ('city_name', models.CharField(blank=True, max_length=31, null=True, verbose_name='Miasto')),
                ('street_name', models.CharField(blank=True, max_length=127, null=True, verbose_name='Ulica')),
                ('home_number', models.CharField(blank=True, max_length=63, null=True, verbose_name='Dom/Mieszkanie')),
                ('promocode', models.CharField(blank=True, max_length=63, null=True, verbose_name='Kod promo')),
                ('lookup', models.CharField(max_length=255)),
                ('calculator_enabled', models.BooleanField(default=True, verbose_name='Dostępny kalkulator')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
                ('user_top', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest_api.UserPrivate', verbose_name='Zarządca')),
            ],
            options={
                'verbose_name': 'Uzytkownik',
                'verbose_name_plural': 'Uzytkownicy',
            },
        ),
        migrations.CreateModel(
            name='WatchAuction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Auction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WatchTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=127)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userbusiness',
            name='user_top',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest_api.UserPrivate', verbose_name='Zarządca'),
        ),
        migrations.AddField(
            model_name='auction',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Brand', verbose_name='Marka'),
        ),
        migrations.CreateModel(
            name='BetSupervisor',
            fields=[
            ],
            options={
                'verbose_name': 'Licytacja',
                'verbose_name_plural': 'Licytacje Podopiecznych',
                'proxy': True,
            },
            bases=('rest_api.bet',),
        ),
    ]
