# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2020-08-11 01:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, verbose_name='Nazwa kampani')),
                ('cookie_value', models.CharField(max_length=63, verbose_name='Wartość Cookiesa')),
                ('url_string', models.CharField(max_length=63, verbose_name='Fragment referencyjnego URL lub Referer')),
            ],
            options={
                'verbose_name': 'Kampania Marketingowa',
                'verbose_name_plural': 'Kampanie Marketingowe',
            },
        ),
        migrations.AddField(
            model_name='scheduledbet',
            name='is_aggressive',
            field=models.BooleanField(default=False, verbose_name='Automat agresywny'),
        ),
        migrations.AddField(
            model_name='userprivate',
            name='registered_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 11, 1, 13, 29, 746467), verbose_name='Data rejestracji'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprivate',
            name='campaign_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest_api.MarketingCampaign', verbose_name='Kampania źródłowa'),
        ),
    ]
