# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-03-14 16:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20200811_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprivate',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
    ]
