# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-03-14 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_auto_20210314_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomateDashboardModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Panel Zarządzania Automatyzacją',
                'verbose_name_plural': 'Panel Zarządzania Automatyzacją',
            },
        ),
    ]
