# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-04-03 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_automatedashboardmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetNotificationsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=64, verbose_name='Nr telefonu')),
                ('activated', models.BooleanField(default=False, verbose_name='Aktywowany')),
            ],
            options={
                'verbose_name_plural': 'Powiadomienia SMS',
                'verbose_name': 'Powiadomienia SMS',
            },
        ),
    ]
