# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-04-25 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_betnotificationsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='betnotificationsmodel',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data zakończenia'),
        ),
    ]
