# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-06-26 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_betnotificationsmodel_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='end_date',
            field=models.DateTimeField(verbose_name='Zakończenie'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Opublikowany'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['-end_date'], name='rest_api_au_end_dat_53d5fe_idx'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['provider_name'], name='rest_api_au_provide_8aaea5_idx'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['-provider_id'], name='rest_api_au_provide_251181_idx'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['ref_id'], name='rest_api_au_ref_id_401fef_idx'),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['-date'], name='rest_api_be_date_f3596c_idx'),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['user', '-price'], name='rest_api_be_user_id_ff4630_idx'),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['user'], name='rest_api_be_user_id_f92f9a_idx'),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['-date', 'user', '-price'], name='rest_api_be_date_71e90f_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledbet',
            index=models.Index(fields=['-bet'], name='rest_api_sc_bet_id_595c2e_idx'),
        ),
    ]
