# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2022-01-22 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0007_auto_20210626_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='subprovider_name',
            field=models.CharField(default='', max_length=127, verbose_name='Sprzedający'),
        ),
    ]
