# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2022-02-05 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0008_auction_subprovider_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='vin',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='VIN'),
        ),
    ]
