# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2022-02-05 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0009_bet_vin'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='invoice_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cena na fakturze [CHF]'),
        ),
    ]
