# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2024-02-23 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0016_auto_20240223_0406'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bet',
            name='rest_api_be_user_id_ff4630_idx',
        ),
        migrations.RemoveIndex(
            model_name='bet',
            name='rest_api_be_user_id_f92f9a_idx',
        ),
        migrations.RemoveIndex(
            model_name='bet',
            name='rest_api_be_auction_996539_idx',
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['id', 'auction_id', '-auction_end_date'], name='rest_api_be_id_54aab0_idx'),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['user_id'], name='rest_api_be_user_id_f92f9a_idx'),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['user_priv_id'], name='rest_api_be_user_pr_769c76_idx'),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['auction_end_date'], name='rest_api_be_auction_d6fc4f_idx'),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['color'], name='rest_api_be_color_b5195d_idx'),
        ),
    ]
